Repository wecode-bootcamp-korea/39-1st-PickEat-frontend, pull requests merged in 2022-11, with the labels that each got.

#4 [39기 윤수민] : 홈페이지 상단 nav바 90%완료 추가기능 구현중
  src/Router.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/NavBar.scss
Labels: 수정 요청, 추가 기능 구현 중

#5 [39기 윤수민] : 메인페이지 레이아웃,기능 완료 추가레이아웃 구현중
  public/data/aa.json
  public/data/bastLecture.json
  public/data/freeLecture.json
  public/data/slidedata.json
  public/images/채소사진.jpg
  src/components/NavBar/NavBar.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/BastLecture/BastLecture.js
  src/pages/Main/components/BastLecture/BastLecture.scss
  src/pages/Main/components/Slideshow/Slideshow.js
  src/pages/Main/components/Slideshow/Slideshow.scss
  src/pages/Main/components/freeLecture/FreeLecture.js
  src/pages/Main/components/freeLecture/FreeLecture.scss
Labels: 추가 기능 구현 중

#9 [39기 윤수민] ADD : 카테고리 페이지 70%완료 필터링기능 구현중
  public/data/categoryData.json
  public/data/freeLecture.json
  src/Router.js
  src/components/NavBar/NavBar.js
  src/pages/DetailPage/DetailPage.js
  src/pages/DetailPage/DetailPage.scss
  src/pages/DetailPage/component/category/Category.js
  src/pages/DetailPage/component/category/Category.scss
  src/pages/DetailPage/component/lecture/Lectures.js
  src/pages/DetailPage/component/lecture/Lectures.scss
Labels: 추가 기능 구현 중

#14 [39기 김보윤] ADD: 새로운 브랜치 생성함 newProductDetailPage
  src/Router.js
  src/pages/DetailPage/ProductDetailPage.js
  src/pages/DetailPage/ProductDetailPage.scss
  src/pages/DetailPage/ReviewList.js
  src/pages/DetailPage/ReviewList.scss
Labels: 멘토 리뷰 요청

#13 [39기 김보윤] ADD: 새로운 브랜치 생성 newLectureDetailPage
  src/Router.js
  src/pages/DetailPage/LectureDetailPage.js
  src/pages/DetailPage/LectureDetailPage.scss
Labels: 멘토 리뷰 요청

#7 [39기 천정환] ADD:로그인, 약관동의, 회원가입 ,footer, Top버튼 최종 merge 요청합니다.
  public/images/default_profile.png
  public/index.html
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/NavBar/NavBar.js
  src/components/TopBtn/TopBtn.js
  src/components/TopBtn/TopBtn.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/Signup/SignUp.scss
  src/pages/Signup/Signup.js
  src/pages/Terms/Terms.js
  src/pages/Terms/Terms.scss
  src/pages/UserForm/UserForm.js
  src/pages/UserForm/UserForm.scss
Labels: 멘토 리뷰 요청

#12 [39기 김보윤] ADD: 새로운 브랜치 다시 생성함 newShoppingCart
  src/pages/ShoppingCart/CartLectureList.js
  src/pages/ShoppingCart/CartLecureList.scss
  src/pages/ShoppingCart/CartProductList.js
  src/pages/ShoppingCart/CartProductList.scss
  src/pages/ShoppingCart/ShoppingCart.js
  src/pages/ShoppingCart/ShoppingCart.scss
Labels: 멘토 리뷰 요청

#15 [39기 김보윤] ADD: 충돌 해결
  src/pages/DetailPage/LectureDetailPage.js
  src/pages/ShoppingCart/AsideCart.js
  src/pages/ShoppingCart/AsideCart.scss
  src/pages/ShoppingCart/CartLectureList.scss
Labels: 멘토 리뷰 요청

#16 [39기 윤수민] ADD : 최종 수정완료 머지 부탁드립니다!
  src/Router.js
  src/components/NavBar/component/UserBar/ShoppingBasket.js
  src/pages/DetailPage/LectureDetailPage.scss
  src/pages/DetailPage/component/lecture/Lectures.js
  src/pages/Main/components/BastLecture/BastLecture.js
  src/pages/Main/components/freeLecture/FreeLecture.js
  src/pages/ShoppingCart/ShoppingCart.js
  src/pages/ShoppingPage/component/lecture/Lectures.js
Labels: 멘토 리뷰 요청
